/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.sarav.food.order;
@org.apache.avro.specific.AvroGenerated
public enum paymentOrderStatus implements org.apache.avro.generic.GenericEnumSymbol<paymentOrderStatus> {
  PENDING, CANCELLED, PAID  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"paymentOrderStatus\",\"namespace\":\"org.sarav.food.order\",\"symbols\":[\"PENDING\",\"CANCELLED\",\"PAID\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
